// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersianMemo.Models;

namespace PersianMemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220204213542_AlteredSeedData2")]
    partial class AlteredSeedData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersianMemo.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("PersianWord")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PronunciationPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = 1,
                            PersianWord = "ایران",
                            PhotoPath = "bac074b4 - 83ad - 4ec5 - 8b8a - e498fe02e048_Iran.png",
                            PronunciationPath = "d4838478-2fba-4c1c-864d-21c8cc6f941e_pronunciation_fa_ایران.mp3",
                            Translation = "Iran"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
